.TH "stdio Directory Reference" 3 "Tue Aug 12 2014" "Version 1.8.1" "avr-libc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stdio Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBclearerr\&.c\fP"
.br
.ti -1c
.RI "file \fBfclose\&.c\fP"
.br
.ti -1c
.RI "file \fBfdevopen\&.c\fP"
.br
.ti -1c
.RI "file \fBfeof\&.c\fP"
.br
.ti -1c
.RI "file \fBferror\&.c\fP"
.br
.ti -1c
.RI "file \fBfgetc\&.c\fP"
.br
.ti -1c
.RI "file \fBfgets\&.c\fP"
.br
.ti -1c
.RI "file \fBfprintf\&.c\fP"
.br
.ti -1c
.RI "file \fBfprintf_p\&.c\fP"
.br
.ti -1c
.RI "file \fBfputc\&.c\fP"
.br
.ti -1c
.RI "file \fBfputs\&.c\fP"
.br
.ti -1c
.RI "file \fBfputs_p\&.c\fP"
.br
.ti -1c
.RI "file \fBfread\&.c\fP"
.br
.ti -1c
.RI "file \fBfscanf\&.c\fP"
.br
.ti -1c
.RI "file \fBfscanf_p\&.c\fP"
.br
.ti -1c
.RI "file \fBfwrite\&.c\fP"
.br
.ti -1c
.RI "file \fBgetc\&.S\fP"
.br
.ti -1c
.RI "file \fBgetchar\&.c\fP"
.br
.ti -1c
.RI "file \fBgets\&.c\fP"
.br
.ti -1c
.RI "file \fBiob\&.c\fP"
.br
.ti -1c
.RI "file \fBprintf\&.c\fP"
.br
.ti -1c
.RI "file \fBprintf_p\&.c\fP"
.br
.ti -1c
.RI "file \fBputc\&.S\fP"
.br
.ti -1c
.RI "file \fBputchar\&.c\fP"
.br
.ti -1c
.RI "file \fBputs\&.c\fP"
.br
.ti -1c
.RI "file \fBputs_p\&.c\fP"
.br
.ti -1c
.RI "file \fBscanf\&.c\fP"
.br
.ti -1c
.RI "file \fBscanf_p\&.c\fP"
.br
.ti -1c
.RI "file \fBsnprintf\&.c\fP"
.br
.ti -1c
.RI "file \fBsnprintf_p\&.c\fP"
.br
.ti -1c
.RI "file \fBsprintf\&.c\fP"
.br
.ti -1c
.RI "file \fBsprintf_p\&.c\fP"
.br
.ti -1c
.RI "file \fBsscanf\&.c\fP"
.br
.ti -1c
.RI "file \fBsscanf_p\&.c\fP"
.br
.ti -1c
.RI "file \fBstdio_private\&.h\fP"
.br
.ti -1c
.RI "file \fBultoa_invert\&.S\fP"
.br
.ti -1c
.RI "file \fBungetc\&.c\fP"
.br
.ti -1c
.RI "file \fBvfprintf\&.c\fP"
.br
.ti -1c
.RI "file \fBvfprintf_p\&.c\fP"
.br
.ti -1c
.RI "file \fBvfscanf\&.c\fP"
.br
.ti -1c
.RI "file \fBvfscanf_p\&.c\fP"
.br
.ti -1c
.RI "file \fBvprintf\&.c\fP"
.br
.ti -1c
.RI "file \fBvscanf\&.c\fP"
.br
.ti -1c
.RI "file \fBvsnprintf\&.c\fP"
.br
.ti -1c
.RI "file \fBvsnprintf_p\&.c\fP"
.br
.ti -1c
.RI "file \fBvsprintf\&.c\fP"
.br
.ti -1c
.RI "file \fBvsprintf_p\&.c\fP"
.br
.ti -1c
.RI "file \fBxtoa_fast\&.h\fP"
.br
.in -1c
