.TH "pmstring Directory Reference" 3 "Tue Aug 12 2014" "Version 1.8.1" "avr-libc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pmstring Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmemccpy_P\&.S\fP"
.br
.ti -1c
.RI "file \fBmemchr_P\&.S\fP"
.br
.ti -1c
.RI "file \fBmemcmp_P\&.S\fP"
.br
.ti -1c
.RI "file \fBmemcmp_PF\&.S\fP"
.br
.ti -1c
.RI "file \fBmemcpy_P\&.S\fP"
.br
.ti -1c
.RI "file \fBmemcpy_PF\&.S\fP"
.br
.ti -1c
.RI "file \fBmemrchr_P\&.S\fP"
.br
.ti -1c
.RI "file \fBstrcasecmp_P\&.S\fP"
.br
.ti -1c
.RI "file \fBstrcasecmp_PF\&.S\fP"
.br
.ti -1c
.RI "file \fBstrcat_P\&.S\fP"
.br
.ti -1c
.RI "file \fBstrcat_PF\&.S\fP"
.br
.ti -1c
.RI "file \fBstrchr_P\&.S\fP"
.br
.ti -1c
.RI "file \fBstrchrnul_P\&.S\fP"
.br
.ti -1c
.RI "file \fBstrcmp_P\&.S\fP"
.br
.ti -1c
.RI "file \fBstrcmp_PF\&.S\fP"
.br
.ti -1c
.RI "file \fBstrcpy_P\&.S\fP"
.br
.ti -1c
.RI "file \fBstrcpy_PF\&.S\fP"
.br
.ti -1c
.RI "file \fBstrcspn_P\&.S\fP"
.br
.ti -1c
.RI "file \fBstrlcat_P\&.S\fP"
.br
.ti -1c
.RI "file \fBstrlcat_PF\&.S\fP"
.br
.ti -1c
.RI "file \fBstrlcpy_P\&.S\fP"
.br
.ti -1c
.RI "file \fBstrlcpy_PF\&.S\fP"
.br
.ti -1c
.RI "file \fBstrlen_P\&.S\fP"
.br
.ti -1c
.RI "file \fBstrlen_PF\&.S\fP"
.br
.ti -1c
.RI "file \fBstrncasecmp_P\&.S\fP"
.br
.ti -1c
.RI "file \fBstrncasecmp_PF\&.S\fP"
.br
.ti -1c
.RI "file \fBstrncat_P\&.S\fP"
.br
.ti -1c
.RI "file \fBstrncat_PF\&.S\fP"
.br
.ti -1c
.RI "file \fBstrncmp_P\&.S\fP"
.br
.ti -1c
.RI "file \fBstrncmp_PF\&.S\fP"
.br
.ti -1c
.RI "file \fBstrncpy_P\&.S\fP"
.br
.ti -1c
.RI "file \fBstrncpy_PF\&.S\fP"
.br
.ti -1c
.RI "file \fBstrnlen_P\&.S\fP"
.br
.ti -1c
.RI "file \fBstrnlen_PF\&.S\fP"
.br
.ti -1c
.RI "file \fBstrpbrk_P\&.S\fP"
.br
.ti -1c
.RI "file \fBstrrchr_P\&.S\fP"
.br
.ti -1c
.RI "file \fBstrsep_P\&.S\fP"
.br
.ti -1c
.RI "file \fBstrspn_P\&.S\fP"
.br
.ti -1c
.RI "file \fBstrstr_P\&.S\fP"
.br
.ti -1c
.RI "file \fBstrstr_PF\&.S\fP"
.br
.ti -1c
.RI "file \fBstrtok_P\&.c\fP"
.br
.ti -1c
.RI "file \fBstrtok_rP\&.S\fP"
.br
.in -1c
