.TH "string Directory Reference" 3 "Tue Aug 12 2014" "Version 1.8.1" "avr-libc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
string Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBffs\&.S\fP"
.br
.ti -1c
.RI "file \fBffsl\&.S\fP"
.br
.ti -1c
.RI "file \fBffsll\&.S\fP"
.br
.ti -1c
.RI "file \fBmemccpy\&.S\fP"
.br
.ti -1c
.RI "file \fBmemchr\&.S\fP"
.br
.ti -1c
.RI "file \fBmemcmp\&.S\fP"
.br
.ti -1c
.RI "file \fBmemcpy\&.S\fP"
.br
.ti -1c
.RI "file \fBmemmem\&.S\fP"
.br
.ti -1c
.RI "file \fBmemmem_P\&.S\fP"
.br
.ti -1c
.RI "file \fBmemmove\&.S\fP"
.br
.ti -1c
.RI "file \fBmemrchr\&.S\fP"
.br
.ti -1c
.RI "file \fBmemset\&.S\fP"
.br
.ti -1c
.RI "file \fBstrcasecmp\&.S\fP"
.br
.ti -1c
.RI "file \fBstrcasestr\&.S\fP"
.br
.ti -1c
.RI "file \fBstrcasestr_P\&.S\fP"
.br
.ti -1c
.RI "file \fBstrcat\&.S\fP"
.br
.ti -1c
.RI "file \fBstrchr\&.S\fP"
.br
.ti -1c
.RI "file \fBstrchrnul\&.S\fP"
.br
.ti -1c
.RI "file \fBstrcmp\&.S\fP"
.br
.ti -1c
.RI "file \fBstrcpy\&.S\fP"
.br
.ti -1c
.RI "file \fBstrcspn\&.S\fP"
.br
.ti -1c
.RI "file \fBstrdup\&.c\fP"
.br
.ti -1c
.RI "file \fBstrlcat\&.c\fP"
.br
.ti -1c
.RI "file \fBstrlcat\&.S\fP"
.br
.ti -1c
.RI "file \fBstrlcpy\&.c\fP"
.br
.ti -1c
.RI "file \fBstrlcpy\&.S\fP"
.br
.ti -1c
.RI "file \fBstrlen\&.S\fP"
.br
.ti -1c
.RI "file \fBstrlwr\&.S\fP"
.br
.ti -1c
.RI "file \fBstrncasecmp\&.S\fP"
.br
.ti -1c
.RI "file \fBstrncat\&.S\fP"
.br
.ti -1c
.RI "file \fBstrncmp\&.S\fP"
.br
.ti -1c
.RI "file \fBstrncpy\&.S\fP"
.br
.ti -1c
.RI "file \fBstrnlen\&.S\fP"
.br
.ti -1c
.RI "file \fBstrpbrk\&.S\fP"
.br
.ti -1c
.RI "file \fBstrrchr\&.S\fP"
.br
.ti -1c
.RI "file \fBstrrev\&.S\fP"
.br
.ti -1c
.RI "file \fBstrsep\&.S\fP"
.br
.ti -1c
.RI "file \fBstrspn\&.S\fP"
.br
.ti -1c
.RI "file \fBstrstr\&.S\fP"
.br
.ti -1c
.RI "file \fBstrtok\&.c\fP"
.br
.ti -1c
.RI "file \fBstrtok_r\&.S\fP"
.br
.ti -1c
.RI "file \fBstrupr\&.S\fP"
.br
.in -1c
