.TH "include Directory Reference" 3 "Tue Aug 12 2014" "Version 1.8.1" "avr-libc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBavr\fP"
.br
.ti -1c
.RI "directory \fBcompat\fP"
.br
.ti -1c
.RI "directory \fButil\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBalloca\&.h\fP"
.br
.ti -1c
.RI "file \fBassert\&.h\fP"
.br
.ti -1c
.RI "file \fBctype\&.h\fP"
.br
.ti -1c
.RI "file \fBerrno\&.h\fP"
.br
.ti -1c
.RI "file \fBinttypes\&.h\fP"
.br
.ti -1c
.RI "file \fBmath\&.h\fP"
.br
.ti -1c
.RI "file \fBsetjmp\&.h\fP"
.br
.ti -1c
.RI "file \fBstdint\&.h\fP"
.br
.ti -1c
.RI "file \fBstdio\&.h\fP"
.br
.ti -1c
.RI "file \fBstdlib\&.h\fP"
.br
.ti -1c
.RI "file \fBstring\&.h\fP"
.br
.ti -1c
.RI "file \fBtime\&.h\fP"
.br
.in -1c
