.TH "compat Directory Reference" 3 "Tue Aug 12 2014" "Version 1.8.1" "avr-libc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
compat Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdeprecated\&.h\fP"
.br
.ti -1c
.RI "file \fBina90\&.h\fP"
.br
.ti -1c
.RI "file \fBcompat/twi\&.h\fP"
.br
.in -1c
