.TH "acks" 3 "Tue Aug 12 2014" "Version 1.8.1" "avr-libc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
acks \- Acknowledgments 
This document tries to tie together the labors of a large group of people\&. Without these individuals' efforts, we wouldn't have a terrific, \fI\fBfree\fP\fP set of tools to develop AVR projects\&. We all owe thanks to: 
.PP
.nf
- The GCC Team, which produced a very capable set of development tools for
an amazing number of platforms and processors.

- Denis Chertykov [ denisc@overta.ru ] for making the AVR-specific changes
to the GNU tools.

- Denis Chertykov and Marek Michalkiewicz [ marekm@linux.org.pl ] for
developing the standard libraries and startup code for \b AVR-GCC.

- Uros Platise for developing the AVR programmer tool, \b uisp.

- Joerg Wunsch [ joerg@FreeBSD.ORG ] for adding all the AVR development
tools to the FreeBSD [ http://www.freebsd.org ] ports tree and for
providing the basics for the \ref demo_project "demo project".

- Brian Dean [ bsd@bsdhome.com ] for developing \b avrdude (an alternative
to <b>uisp</b>) and for contributing \ref using_avrprog "documentation"
which describes how to use it. \b Avrdude was previously called 
\b avrprog.

- Eric Weddington [ eweddington@cso.atmel.com ] for maintaining the \b WinAVR
package and thus making the continued improvements to the
open source AVR toolchain available to many users.

- Rich Neswold for writing the original avr-tools document (which he
graciously allowed to be merged into this document) and his
improvements to the \ref demo_project "demo project".

- Theodore A. Roth for having been a long-time maintainer of
many of the tools (\b AVR-Libc, the AVR port of \b GDB, \b AVaRICE,
\b uisp, \b avrdude).

- All the people who currently maintain the tools, and/or
have submitted suggestions, patches and bug reports.

.fi
.PP
 (See the AUTHORS files of the various tools\&.) 
.PP
.nf
- And lastly, all the users who use the software. If nobody used the
software, we would probably not be very motivated to continue to develop
it. Keep those bug reports coming. ;-)
.fi
.PP
 
