.TH "ldiv_t" 3 "Tue Aug 12 2014" "Version 1.8.1" "avr-libc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ldiv_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "long \fBquot\fP"
.br
.ti -1c
.RI "long \fBrem\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Result type for function \fBldiv()\fP\&. 
.SH "Field Documentation"
.PP 
.SS "long ldiv_t::quot"
The Quotient\&. 
.SS "long ldiv_t::rem"
The Remainder\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for avr-libc from the source code\&.
